config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :projects do
    resources :events
  end

  resources :webhooks

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]

  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'


  authenticated :user do
    root to: "projects#index", as: :authenticated_root
  end

  root to: 'home#index'
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :events

  has_secure_token
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = current_user.projects
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @pagy, @events = pagy(@project.events.order(created_at: :desc))
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = current_user.projects.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <% if project.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', project, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if project.persisted? %>
      <%= link_to "Cancel", project, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", projects_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render 'form', project: @project %>

app/views/projects/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Projects</h1>
  </div>

  <div class="col-sm-6 text-right">
  <%= link_to new_project_path, class: 'btn btn-primary' do %>
    Add New Project
  <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Events</th>
      </tr>
    </thead>

    <tbody>
      <% @projects.each do |project| %>
        <%= content_tag :tr, id: dom_id(project), class: dom_class(project) do %>
            <td><%= link_to project.name, project %></td>
            <td><%= project.events_count %></td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form', project: @project %>

app/views/projects/show.html.erb
<div class="page-header">
  <div class="d-flex justify-content-between">
    <h1 class="h4">
      <%= link_to @project.name, @project, class: "font-weight-normal" %>
    </h1>
    <%= link_to "Edit Project", edit_project_path(@project) %>
  </div>
</div>

<div class="mb-4">
  Send webhooks to:
  <code class="ml-1 text-monospace"><%= webhooks_url(token: @project.token) %></code>
</div>

<h5><%= pluralize @project.events_count, "Event" %></h5>
<% @events.each do |event| %>
  <div>
    <%= link_to event.created_at, project_event_path(@project, event) %>
  </div>
<% end %>

<%== pagy_bootstrap_nav(@pagy) %>